services:
  postgres:
    image: postgres:latest
    ports:
      - '5932:5432' # expose pg on port 5932 to not collide with pg from elsewhere
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
  valkey:
    image: valkey/valkey
    ports:
      - '6379:6379'
volumes:
  db_data:
