services:
  postgres:
    image: postgres:latest
    ports:
      - '5932:5432' # expose pg on port 5932 to not collide with pg from elsewhere
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust

  valkey-node-0:
    image: 'bitnami/valkey-cluster:latest'
    volumes:
      - valkey-cluster_data-0:/bitnami/valkey/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=true'
      - 'VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-node-5'

  valkey-node-1:
    image: 'bitnami/valkey-cluster:latest'
    volumes:
      - valkey-cluster_data-1:/bitnami/valkey/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=true'
      - 'VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-node-5'

  valkey-node-2:
    image: 'bitnami/valkey-cluster:latest'
    volumes:
      - valkey-cluster_data-2:/bitnami/valkey/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=true'
      - 'VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-node-5'

  valkey-node-3:
    image: 'bitnami/valkey-cluster:latest'
    volumes:
      - valkey-cluster_data-3:/bitnami/valkey/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=true'
      - 'VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-node-5'

  valkey-node-4:
    image: 'bitnami/valkey-cluster:latest'
    volumes:
      - valkey-cluster_data-4:/bitnami/valkey/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=true'
      - 'VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-node-5'

  valkey-node-5:
    image: 'bitnami/valkey-cluster:latest'
    volumes:
      - valkey-cluster_data-5:/bitnami/valkey/data
    depends_on:
      - valkey-node-0
      - valkey-node-1
      - valkey-node-2
      - valkey-node-3
      - valkey-node-4
    environment:
      - 'ALLOW_EMPTY_PASSWORD=true'
      - 'VALKEY_CLUSTER_REPLICAS=1'
      - 'VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-node-5'
      - 'VALKEY_CLUSTER_CREATOR=yes'


volumes:
  db_data:
    driver: local
  valkey-cluster_data-0:
    driver: local
  valkey-cluster_data-1:
    driver: local
  valkey-cluster_data-2:
    driver: local
  valkey-cluster_data-3:
    driver: local
  valkey-cluster_data-4:
    driver: local
  valkey-cluster_data-5:
    driver: local
